### ISSUE TITLE
nemo downgrades npm for my package

### ISSUE THREAD

**Issue by aredridel** [paypal/nemo#102]
`nemo` installs `npmi` installs `npm@2`

installed with `npm@3`, this means that `npm@2` ends up in the root `./node_modules/.bin`, meaning further installs in that directory from npm scripts run `npm@2` not `npm@3`

This actually broke my entire `node_modules` since npm@2 really doesn't like my npm@3 installed tree.

**Comment by grawk** [comment]
Yikes! `npmi` is a relatively recent change. I wonder if we should roll that back @nikulkarni .. Anyway, we will investigate. Thanks.

**Comment by aredridel** [comment]
Yeah! Surprised the heck out of me!

**Comment by grawk** [comment]
Looks like `npmi` is in the process of updating for `npm@3`: https://github.com/maxleiko/npmi/issues/5

You should be able to peg to the prior minor version of `nemo` to avoid this for now.

**Comment by aredridel** [comment]
Yeah, I actually depended on `npm` to force npm 2 into a sub directory.

I'd suggest just replacing npmi with a simple `child_process` though

**Comment by grawk** [comment]
So you added `npm` as a dependency to your main project to work around this? Sorry, just curious about that bit. Yeah we will look into removing the dependency on this `npmi` module. It's an additional headache I don't want to manage here.

**Comment by grawk** [comment]
@nikulkarni i think we should unpublish this minor release (in both the `v1` and `v2` releases) and re-release it on an experimental tag. How many users would be affected, do you know?

**Comment by grawk** [comment]
What I'll do is the following:
1. unpublish `v2.1.0` and `v1.1.1` (these two have only the `npmi` change)
2. re-publish the `npmi`-related feature as `v2.1.0-alpha.1`
3. other feature development continues as required
4. the `npmi`-related feature development continues on the alpha series until this side effect is eliminated

Will wait on this until Sunday or Monday to give time for discussion.

**Comment by grawk** [comment]
I've moved the `selenium.version` feature which uses `npmi` to a branch, `2.1.0-alpha.1` and published the feature as `nemo@v2.1.0-alpha.1`. I've unpublished `v2.1.0` which means that specifying `nemo@^v2.0.0` you will no longer get the breaking change described here.

**Comment by grawk** [comment]
I did what @aredridel suggested and replaced `npmi` with `child_process.exec`. published as `2.1.0-alpha.2`
