### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by gabrielcsapo** [paypal/nemo#116]
readme seems to have outdated information, should be updated to accommodate new features and examples.

<img width="960" alt="screen shot 2016-04-14 at 6 41 42 pm" src="https://cloud.githubusercontent.com/assets/1854811/14548980/9c56ca24-0270-11e6-9980-a8fab4dcef11.png">

**Comment by grawk** [comment]
yeah. that bit could be fixed by instead saying `npm install --save-dev nemo`

**Comment by grawk** [comment]
I guess let's limit the scope of this bug to that particular bit you mentioned. Unless you want to edit the main description with additional discrepancies.

**Comment by gabrielcsapo** [comment]
@grawk I think using ```npm install --save-dev nemo``` works :smile:
