### ISSUE TITLE
implement additional shortstop-handlers

### ISSUE THREAD

**Issue by grawk** [paypal/nemo#119]
https://github.com/paypal/nemo/blob/master/index.js#L82-L91

E.g. `require` and `glob` could be useful
https://github.com/krakenjs/shortstop-handlers#api

**Comment by jonathansamines** [comment]
Hey @grawk  may I PR this change?

**Comment by grawk** [comment]
@jonathansamines yes of course. that would be great.

**Comment by gabrielcsapo** [comment]
looks like an open PR #151 has the fix.

**Comment by skratchdot** [comment]
closing since this has been fixed in #151
