### ISSUE TITLE
add CONTRIBUTING.md

### ISSUE THREAD

**Issue by grawk** [paypal/nemo#15]
Spell out the contribution steps, as well as branching and release strategy in a markdown document

**Comment by grawk** [comment]
Have a document in the nemo-docs repo here now: https://github.com/paypal/nemo-docs/blob/develop/contributing.md

Can close this issue once remainder of items is added to contributing.md and also once the README of nemo is pointing to it.

**Comment by gabrielcsapo** [comment]
@grawk is https://github.com/paypal/nemo-docs/blob/develop/contributing.md still a valid file for contributing?

**Comment by grawk** [comment]
yeah. though that doc probably needs an update. we can close this issue here.
