### ISSUE TITLE
Display the actual element when "Uncaught ElementNotVisibleError: element not visible" is caught

### ISSUE THREAD

**Issue by lucy5533** [paypal/nemo#17]
When "Uncaught ElementNotVisibleError: element not visible" or some error similar to this is caught, developers have to dig into the trace log o find more information. With a lot of text to dig, it will be much easier for our eyes and save time if the log tells the problem element up front (the first red line).

**Comment by grawk** [comment]
@lucy5533 can you let me know if you were using `nemo-view` in your test suite? I suspect we should open this issue there. The main nemo module simply deals with startup of the driver and initialization of the plugins.
