### ISSUE TITLE
selenium-webdriver in package.json - 2.45.1 needed for Firefox 37.0.2 on OS/X

### ISSUE THREAD

**Issue by masotime** [paypal/nemo#63]
If it doesn't break compatibility, maybe use `^2` in package.json rather than `~2.44.0`? see https://github.com/paypal/nemo/blob/master/package.json#L15

**Comment by grawk** [comment]
Hi @masotime. Last time I checked, the latest selenium-webdriver `2.45.1` wouldn't run _any_ browsers correctly on my machine. We are very careful when updating the webdriver version and recommend users not automatically update their browsers as webdriver support typically lags behind any breaking changes in new browser releases. I think we need to add a section in the README (or a separate doc) to track browser version compatibility.

In the meantime, I recommend downgrading to Firefox 35.

**Comment by masotime** [comment]
Thanks @grawk for the quick response. I'll keep that in mind.
