### ISSUE TITLE
Mocha tests fail

### ISSUE THREAD

**Issue by benmarten** [paypal/nemo#64]
When running: `mocha`

I get:
7 passing (10s)
5 failing

**Comment by grawk** [comment]
Hi @benmarten,

The tests are passing in CI. They pass for me locally as well. The tests do rely upon opening up a heroku app. I wonder if you are experiencing timeouts due to slowness of loading that app.

Can you share a more detailed accounting of the failures and stack traces?

**Comment by benmarten** [comment]
Yes, it seems to timeout:

  1) @constructor@ should launch nemo with @envConfigPath@noOverrideArg@:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
  

  2) @constructor@ should launch nemo with @argConfigPath@noOverrideArg@:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
  

  3) @constructor@ should launch nemo with @allArgs@:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
  

  4) @proxy@  should load problem loading page error:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

When I run them with: `grunt`  - all work... didn't know... we can probably close this then...

**Comment by grawk** [comment]
Ah, you're running mocha directly. The `simplemocha` task has a timeout of 15 seconds or so. If you provide the correct argv to mocha I suspect all the tests will pass. But it will be far easier just to run `grunt` or `npm test`.

**Comment by grawk** [comment]
Just checked. Timeout is 30 seconds.
