### ISSUE TITLE
Improve Error Message of Plugin Error

### ISSUE THREAD

**Issue by benmarten** [paypal/nemo#65]
I am working on a nemo plugin and see this very often:

	Error during Nemo setup { [nemoNoPluginModuleError: Nemo plugin has invalide module] name: 'nemoNoPluginModuleError' }

It's really hard to find out what the actual issue is... sometimes it's just a single syntax error in the plugin code.

**Comment by benmarten** [comment]
Never mind, I actually find out enabling logging helps :)

    env DEBUG=nemo:log node test/index.js

**Comment by grawk** [comment]
:+1: :)

**Comment by grawk** [comment]
DEBUG=nemo* should display logs from all nemo modules
