### ISSUE TITLE
Make Nemo Work as a Global Command (with Nemo-JSON support)

### ISSUE THREAD

**Issue by benmarten** [paypal/nemo#66]
Hi Matt,

I've spent a few days making the nemo-json plugin work, now I'd like to see if we could make nemo a global command, that allow to run tests directly from command line?

E.g.

Single File: nemo -f myTest.js
Directory: nemo -d myDir/

In addition to that we could support reading JSON test files (via the new nemo-json plugin).
Let me know what you guys think about that? I have a working project, and happy to send a PR if that makes sense for you ;)

**Comment by grawk** [comment]
Thanks. I'd like to know more. Please share your sample project if you don't mind and I can take a look and provide some feedback tomorrow PST

**Comment by grawk** [comment]
I've given some thought to command line runs in general, and I believe that the right way to do this is to have the plugin that requires a command line run to register the CLI during its `npm install` step. So, without having more knowledge of the "nemo-json" plugin, it's impossible to say for sure. But if the command line run is directly tied to usage of the "nemo-json" then that module should manage its CLI.

**Comment by benmarten** [comment]
yes great idea. i totally agree... let me test that and get back to you in a few. thanks

**Comment by grawk** [comment]
closing
