### ISSUE TITLE
Expose nemo.config for plugins?

### ISSUE THREAD

**Issue by benmarten** [paypal/nemo#67]
I need to read which browser nemo is currently using.
Hence how can I access the config.json, including override confit values?

Currently I am using this workaround within the plugin:

	if (process.env.NODE_ENV) {
		var nemoConfigOverride;
		try {
			nemoConfigOverride = rekuire(process.env.NODE_ENV + '.json');
		} catch (err) {
			console.log('Cannot read overrriden config file.');
		}
	}
	var nemoConfig = rekuire('config.json');
	_.assign(nemoConfig, nemoConfigOverride);

I think exposing nemos config at least to its plugins would still be nicer ;)

**Comment by nikulkarni** [comment]
Nemo exposes `_config` object that you can use to read/override configuration. Like

`nemo._config.get('targetBrowser');`
and
`nemo._config.set('userKey','overridewiththisvalue');`

Does this help?

**Comment by nikulkarni** [comment]
Since `_config` is a confit object I believe you can use other methods like `.addOverride('./mysettings.json') //or .addOverride({foo: 'baz'})` as well which I haven't personally used. Check more here https://github.com/krakenjs/confit#config-factory

**Comment by benmarten** [comment]
Good point, unfortunately _config seems to be null:

	console.log(nemo) ...

	_config: null,

that's within the nemo-plugin

**Comment by nikulkarni** [comment]
Thats recently fixed as part of this PR https://github.com/paypal/nemo/pull/62/files

Looks like this is not published yet. I don't have access to publish. @grawk Can you please publish the fix?

**Comment by grawk** [comment]
I will publish the fix and update this issue. I'll also give you publish access @nikulkarni

**Comment by grawk** [comment]
In terms of reading which browser is in use you can also use webdriver methods for that.

**Comment by grawk** [comment]
@benmarten the config change is published as `nemo@1.0.5`. Thus the confit API is exposed via `nemo._config` as documented.

**Comment by benmarten** [comment]
Thanks, works :)
