### ISSUE TITLE
Issues with grunt auto

### ISSUE THREAD

**Issue by NaveenNagendran** [paypal/nemo#74]
grunt auto throws following error : 

1) @flow@ should execute high level functionality using flow modules:
    Uncaught Error: Failure message did not appear
 ==== async task ====
 Failure message did not appear
     at Navigate.loginFailure (testNemo\test\functional\flow\navigate.js:18:31)
     at Context.<anonymous> (testNemo\test\functional\spec\flow-spec.js:25:14)

2) @view@ should execute high level functionality using view methods:
    Uncaught Error: [drivex.waitForElementVisible] Element not visible
 ==== async task ====

--------------------------------------------------------o----------------------------------------------------------

3) Remider : Issues with grunt-loop-mocha as discussed (parallel browser instance issue)
![grunt auto](https://cloud.githubusercontent.com/assets/13139974/8462645/132f8cd6-1fea-11e5-86b8-8da8ef331b5e.JPG)
.

**Comment by grawk** [comment]
Hi @NaveenNagendran. Really appreciate you opening up this issue. However, please can you file it here: https://github.com/paypal/nemo-example-app/issues

Thanks!

**Comment by NaveenNagendran** [comment]
Cool.. Thank you
