### ISSUE TITLE
Still actively maintained?

### ISSUE THREAD

**Issue by jimkang** [paypal/nemo#75]
I thought this looked great a year ago but haven't had time to check it out until now. I just want to check: Are you guys still maintaining it?

**Comment by grawk** [comment]
Oh yeah. We are. Our "media wing" isn't spun up yet but follow our Twitter feed for the latest news. http://twitter.com/nemojs_news

**Comment by jimkang** [comment]
Nice! OK, that's exactly what I wanted to hear.
