### ISSUE TITLE
allow consumer-supplied webdriver module

### ISSUE THREAD

**Issue by grawk** [paypal/nemo#88]
the selenium-webdriver dependency in nemo causes painful upgrade issues when new and desired versions of selenium-webdriver are released. It causes a need for a weird "alpha" period that is only for vetting out new selenium-webdriver versions, and not due to any change in the nemo API

**Comment by grawk** [comment]
testing github/slack integration

**Comment by grawk** [comment]
actually this need not be a breaking/major change. removing 2.0 milestone label

**Comment by nikulkarni** [comment]
Hi I'm working on this and will send a PR soon today

**Comment by nikulkarni** [comment]
This is resolved as part of #98
