### ISSUE TITLE
installation fails with node v4.2.2

### ISSUE THREAD

**Issue by maxmil7** [paypal/nemo#93]
Issue seems to be with utf8-validate and bufferutil modules used by selenium-webdriver

> utf-8-validate@1.1.0 install /Users/mgawande/Desktop/src/scratch/NodeJSTestApp/node_modules/nemo/node_modules/selenium-webdriver/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
Node v4.2.2
NPM 2.14.7

**Comment by nikulkarni** [comment]
This doesn't seem to be a nemo specific issue in my opinion

**Comment by grawk** [comment]
I believe this is resolved with `nemo@^2`

**Comment by nikulkarni** [comment]
@maxmil7 Can you check if this is resolved in `nemo@^2` as Matt suggested above?

**Comment by maxmil7** [comment]
Yes, works with nemo@^2. Closing the issue. Thanks!
